title:   SHRADHANJALI PRADHAN
logo: /assets/My_pic.jpg
description: Welcome to my professional portfolio. I am an AI/ML Engineer with an MSc in Applied Data Analytics from Boston University, passionate about AI advancements and data-driven solutions.
show_downloads: true
theme: jekyll-theme-minimal
