# _config.yml

title: "Shradhanjali Pradhan"
logo: My_pic.jpg  # Make sure you have an 'assets' folder in your repo with 'My_pic.jpg' in it.
description: "AI/ML Engineer | MSc in Applied Data Analytics | Passionate about AI advancements and data-driven solutions."
url: "https://github.com/shradhanjalipradhan" # replace with your actual GitHub Pages URL if different
permalink: "/:title/"
theme: minima
plugins:
  - jekyll-feed

author:
  name: Shradhanjali Pradhan
  bio: "AI/ML Engineer with an MSc in Applied Data Analytics from Boston University. Focused on machine learning models, data quality, and predictive analytics."
  location: United States

social:
  - title: "GitHub"
    url: "https://github.com/shradhanjalipradhan"
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/shradhanjalipradhan"
  - title: "Twitter"
    url: "https://twitter.com/Shradha1405"
  # Add more social links as needed

email: "edu.shradhanjali@gmail.com"
