# Site settings
title: Shradhanjali Pradhan
description: "AI/ML Engineer | MSc in Applied Data Analytics | Passionate about AI accessibility and innovation."
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://shradhanjalipradhan.github.io" # the base hostname & protocol for your site

# Build settings
theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # enabling dark mode

# Site author
author:
  name: Shradhanjali Pradhan
  bio: "MSc in Applied Data Analytics | Driven by the power of data to unlock new potentials in AI and technology."
  location: "United States"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:edu.shradhanjali@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/shradhanjalipradhan"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Shradha1405"
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://github.com/shradhanjalipradhan"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Social sharing
social_links:
  twitter: "Shradha1405"
  linkedin: "shradhanjalipradhan"
  github: "shradhanjalipradhan"
  # Add more social links as needed

# Email
email: "edu.shradhanjali@gmail.com"
